list: $/indev/pagseguro/models/pagseguro/columns.yaml
modelClass: Indev\Pagseguro\Models\Pagseguro
title: PagseguroController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
